//! Rustdoc JSON parsing module.
//!
//! This module handles loading and parsing rustdoc JSON files into the
//! `rustdoc_types::Crate` structure that represents the entire documented crate.
//!
//! # Rustdoc JSON Format
//!
//! Rustdoc JSON is generated by running:
//! ```bash
//! cargo doc --output-format json
//! ```
//!
//! The output is a single JSON file at `target/doc/{crate_name}.json` containing:
//! - The crate's module hierarchy
//! - All public (and optionally private) items
//! - Documentation strings
//! - Type information and generics
//! - Cross-reference links between items
//!
//! # Key Types
//!
//! The parsed `Crate` contains:
//! - `root`: ID of the root module
//! - `index`: `HashMap` of all items by their ID
//! - `paths`: `HashMap` mapping IDs to their full module paths
//! - `crate_version`: Optional version string

use crate::error::Error;
use fs_err as fs;
use rustdoc_types::Crate;
use std::path::Path;

/// Parser for rustdoc JSON files.
///
/// Provides methods to load and parse rustdoc JSON from files or strings
/// into the `rustdoc_types::Crate` structure.
pub struct Parser;

impl Parser {
    /// Parse a rustdoc JSON file from disk into a `Crate` structure.
    ///
    /// This is the primary entry point for loading documentation data.
    /// The file should be generated with `cargo doc --output-format json`.
    ///
    /// # Arguments
    ///
    /// * `path` - Path to the `.json` file (e.g., `target/doc/my_crate.json`)
    ///
    /// # Returns
    ///
    /// A parsed `Crate` structure containing all documentation data.
    ///
    /// # Errors
    ///
    /// Returns `Error::FileRead` if the file cannot be read, or
    /// `Error::JsonParse` if the JSON is invalid or doesn't match
    /// the expected rustdoc JSON schema.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let krate = parse_json(Path::new("target/doc/my_crate.json"))?;
    /// println!("Crate: {:?}", krate.index.get(&krate.root));
    /// ```
    pub fn parse_json(path: &Path) -> Result<Crate, Error> {
        // Read the entire file into memory (rustdoc JSON can be large, but
        // we need it all in memory for serde anyway)
        let content = fs::read_to_string(path).map_err(Error::FileRead)?;

        // Delegate to string parsing
        Self::parse_json_string(&content)
    }

    /// Parse a rustdoc JSON string into a `Crate` structure.
    ///
    /// This function is useful when the JSON content is already in memory
    /// (e.g., fetched from a URL or embedded in tests).
    ///
    /// # Arguments
    ///
    /// * `content` - The raw JSON string to parse
    ///
    /// # Returns
    ///
    /// A parsed `Crate` structure containing all documentation data.
    ///
    /// # Errors
    ///
    /// Returns `Error::JsonParse` if the JSON is invalid or doesn't match
    /// the expected rustdoc JSON schema.
    ///
    /// # Schema Compatibility
    ///
    /// The `rustdoc-types` crate version must match the rustdoc JSON format
    /// version. Mismatches can cause parsing failures or missing fields.
    pub fn parse_json_string(content: &str) -> Result<Crate, Error> {
        // Deserialize the JSON into the Crate type from rustdoc-types.
        // This validates the structure against the expected schema.
        let krate: Crate = serde_json::from_str(content).map_err(Error::JsonParse)?;
        Ok(krate)
    }
}
